from tkinter import *
m1 = Tk()
m1.geometry("500x500")
m1.title("Student Information Entry")
m2=Tk()
m2.geometry("500x500")
m2.title("Student Information Display")

vname=StringVar()
vyear=IntVar()
vbranch=StringVar()
vattendence=StringVar()
vcgpa=StringVar()
vnumber=IntVar()
vaddress=StringVar()

def display():
    name=vname.get()
    year=vyear.get()
    branch=vbranch.get()
    attendence=vattendence.get()
    cgpa=vcgpa.get()
    number=vnumber.get()
    address=vaddress.get()

    l1cm2.config(text=name)
    l2cm2.config(text=year)
    l3cm2.config(text=branch)
    l4cm2.config(text=attendence)
    l5cm2.config(text=cgpa)
    l6cm2.config(text=number)
    l7cm2.config(text=address)

    vname.set("")
    vyear.set("")
    vbranch.set("")
    vattendence.set("")
    vcgpa.set("")
    vnumber.set("")
    vaddress.set("")

    m1.destroy()

l1m1 = Label(m1, text=" student name:-")
e1m1=Entry(m1, width=30, textvariable=vname)
l2m1=Label(m1,text="enter you year:-")
e2m1=Entry(m1, width=30, textvariable=vyear)
l3m1=Label(m1,text="enter your branch:-")
e3m1=Entry(m1, width=30, textvariable=vbranch)
l4m1=Label(m1,text="enter your attendance percentage:-")
e4m1=Entry(m1, width=30, textvariable=vattendence)
l5m1=Label(m1,text="enter your CGPA:-")
e5m1=Entry(m1, width=30, textvariable=vcgpa)
l6m1=Label(m1,text="enter your mobile number:-")
e6m1=Entry(m1, width=30, textvariable=vnumber)
l7m1=Label(m1,text="enter your address:-")
e7m1=Entry(m1, width=60, textvariable=vaddress)
b=Button(m1,text="submit",command=display)

l1m1.grid(row=0,column=0,pady=2)
e1m1.grid(row=0,column=1,pady=2)
l2m1.grid(row=1,column=0,pady=2)
e2m1.grid(row=1,column=1,pady=2)
l3m1.grid(row=2,column=0,pady=2)
e3m1.grid(row=2,column=1,pady=2)
l4m1.grid(row=3,column=0,pady=2)
e4m1.grid(row=3,column=1,pady=2)
l5m1.grid(row=4,column=0,pady=2)
e5m1.grid(row=4,column=1,pady=2)
l6m1.grid(row=5,column=0,pady=2)
e6m1.grid(row=5,column=1,pady=2)
l7m1.grid(row=6,column=0,pady=2)
e7m1.grid(row=6,column=1,pady=2)
b.grid(row=7,column=1,pady=10,padx=3)



l1m2 = Label(m2, text="name of student:-")
l1cm2=Label(m2,text="")
l2m2=Label(m2,text="year of student:-")
l2cm2=Label(m2,text="")
l3m2=Label(m2,text="branch: of student-")
l3cm2=Label(m2,text="")
l4m2=Label(m2,text="attendance percentage of student:-")
l4cm2=Label(m2,text="")
l5m2=Label(m2,text="CGPA of student:-")
l5cm2=Label(m2,text="")
l6m2=Label(m2,text="mobile number of student:-")
l6cm2=Label(m2,text="")
l7m2=Label(m2,text="address of student:-")
l7cm2=Label(m2,text="")


l1m2.grid(row=0,column=0,pady=2)
l1cm2.grid(row=0,column=1,pady=2)
l2m2.grid(row=1,column=0,pady=2)
l2cm2.grid(row=1,column=1,pady=2)
l3m2.grid(row=2,column=0,pady=2)
l3cm2.grid(row=2,column=1,pady=2)
l4m2.grid(row=3,column=0,pady=2)
l4cm2.grid(row=3,column=1,pady=2)
l5m2.grid(row=4,column=0,pady=2)
l5cm2.grid(row=4,column=1,pady=2)
l6m2.grid(row=5,column=0,pady=2)
l6cm2.grid(row=5,column=1,pady=2)
l7m2.grid(row=6,column=0,pady=2)
l7cm2.grid(row=6,column=1,pady=2)
m1.mainloop()
m2.mainloop()